[package]
name = "paydept"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.0"
comfy-table = "5.0.1"
csv = "1.1.6"
jwalk = "0.6.0"
once_cell = "1.9.0"
parking_lot = "0.12.0"
regex = "1.5.4"
url = "2.2.2"
yaml-rust = "0.4.5"
